# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: v4.5.1
_src_path: https://github.com/jupyterlab/extension-template
author_email: luca.ringhausen@h-brs.de
author_name: Luca Ringhausen
has_ai_rules: false
has_binder: false
has_settings: false
kind: frontend
labextension_name: '@e2xgrader-examples/custom-notebook-toolbar'
project_short_description: A JupyterLab extension that adds a custom notebook toolbar.
python_name: e2xgrader_examples_custom_notebook_toolbar
repository: https://github.com/e2xgrader/e2xgrader-extension-examples
test: true

